inherit_from: "configs/rgbd/tum/base_config.yaml"

sequence_name: "rgbd_dataset_freiburg1_desk"
rgb_file: "rgb.txt"
depth_file: "depth.txt"
groundtruth_file: "groundtruth.txt"
associate_file: "associate.txt"


Dataset:
  dataset_path: "/content/MonoGS/datasets/rgbd_dataset_freiburg1_desk"
  Calibration:
    fx: 517.306408
    fy: 516.469215
    cx: 318.643040
    cy: 255.313989
    k1: 0.262383
    k2: -0.953104
    p1: -0.005358
    p2: 0.002628
    k3: 1.163314
    distorted: True
    width: 640
    height: 480
    depth_scale: 5000.0

################## GNC parameters ####################

GNC:
  enabled: true
  s0: 0.3
  s_star: 0.03
  gamma: 0.5
  stages: 5
  iters_per_stage: 10

################ End GNC parameters ####################